### ISSUE TITLE
The AI is stupid

### ISSUE THREAD

**Issue by vincentjguo** [potatoeggy/connectfour#29] opened 2020-06-01 21:34 UTC
helphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelphelp
I need to raise the AI's IQ but how

**Comment by potatoeggy** [comment] 2020-06-01 21:37
increase its search depth

**Comment by vincentjguo** [comment] 2020-06-01 21:38
that just makes it slower at being stupid

**Comment by potatoeggy** [comment] 2020-06-01 21:38
verify your algorithm? is it the correct algorithm?

**Comment by vincentjguo** [comment] 2020-06-01 21:40
probably not, i just realized today that i flipped the AI and player so the AI chose the worst possible option

**Comment by vincentjguo** [comment] 2020-06-01 21:41
this is what happens when you code 200 lines without looking back

**Comment by potatoeggy** [comment] 2020-06-01 21:48
isn't there a way to invert the scores?

**Comment by vincentjguo** [comment] 2020-06-01 21:52
multiply by -1 but i fixed it, it's fine now. But there are still some problems with it

**Comment by potatoeggy** [comment] 2020-06-01 21:58
Is the AI functional right now? Can I call a function that gives me a decision?

**Comment by vincentjguo** [comment] 2020-06-01 22:00
you still need to process it, it will return an arraylist with a list of scores for each position. I can create a function that can process it.

**Comment by potatoeggy** [comment] 2020-06-01 23:17
![image](https://user-images.githubusercontent.com/25178974/83463583-753ac400-a43c-11ea-8f48-48cb955ca030.png)

Hmmmmm
This appears for both Normal and Hard (depths of 3 and 4)

It's really slow. There's very noticeable lag and I have a fairly powerful machine (Ryzen 5 4500U).

**Comment by potatoeggy** [comment] 2020-06-01 23:17
(I'm red)

**Comment by vincentjguo** [comment] 2020-06-01 23:56
is this on master?

**Comment by vincentjguo** [comment] 2020-06-01 23:57
oh by the way the AI has to go first, the player parameter must always be 1

**Comment by potatoeggy** [comment] 2020-06-01 23:57
It's in the ai-gui testing branch

**Comment by vincentjguo** [comment] 2020-06-01 23:58
ok

**Comment by potatoeggy** [comment] 2020-06-01 23:59
right now the identifiers used for players are 1 for player 1, and -1 for player 2

**Comment by vincentjguo** [comment] 2020-06-02 00:01
I have it as player1/AI is 1 and player 2 is 2

**Comment by vincentjguo** [comment] 2020-06-02 00:01
Damn it we should have coordinated this better

**Comment by potatoeggy** [comment] 2020-06-02 00:08
What's the player parameter used for in AI ?

**Comment by vincentjguo** [comment] 2020-06-02 00:43
So basically every time a score is generated, it could either be negative or positive or 0. Negative means P2 has an advantage, positive means the AI has an advantage and 0 is a tie. The AI uses a minimizer and maximizer to figure out what is the best possible move for each side, hence the name minimax as it tries to minimize its losses and maximize its wins. The player parameter basically tells the AI whose turn it is and use the corresponding min/max.

**Comment by vincentjguo** [comment] 2020-06-02 00:44
If you want the AI to go second, call the function after the player moves

**Comment by potatoeggy** [comment] 2020-06-03 18:06
![image](https://user-images.githubusercontent.com/25178974/83671931-776b6280-a5a3-11ea-8118-5dce9daaa38f.png)

**Comment by potatoeggy** [comment] 2020-06-03 18:06
AI is still stupid

**Comment by potatoeggy** [comment] 2020-06-03 19:06
![image](https://user-images.githubusercontent.com/25178974/83678498-d46b1680-a5ab-11ea-8e15-cba1ac155289.png)

**Comment by potatoeggy** [comment] 2020-06-03 19:14
Fixed in 661f221c7042fe30b738282bf45d7855ab7dba75

**Comment by potatoeggy** [comment] 2020-06-04 01:40
![image](https://user-images.githubusercontent.com/25178974/83705397-ca183f00-a5e2-11ea-8f90-16ea764d0f8f.png)
???

Normal difficulty (depth 4)

**Comment by vincentjguo** [comment] 2020-06-04 01:57
is the ai red?

**Comment by potatoeggy** [comment] 2020-06-04 01:59
They're both AIs

Also, the AI tries to make groups of threes even if a group of four would go outside the board

**Comment by vincentjguo** [comment] 2020-06-04 02:00
that... shouldn't happen

**Comment by vincentjguo** [comment] 2020-06-04 02:01
Can you send the code you used to make the AI fight each other? It would help a lot with debugging

**Comment by vincentjguo** [comment] 2020-06-04 02:02
One more question, what's the issue with this?

**Comment by potatoeggy** [comment] 2020-06-04 02:04
I just set both dropdowns to *computer*

the issue is that the ai is dumb and kinda slow. It seems to take exponentially longer after every turn even against humans.

**Comment by potatoeggy** [comment] 2020-06-04 02:05
here's the relevant code chunk in `MainWindow`:
```java
while (win.gameWindow.isVisible() && !win.gameWindow.isGameOver()) { // do not run timer when game is not ongoing
	if (win.gameWindow.getLock()) { // if event thread is waiting for ai calculation
		win.moveTimerInternal = win.moveTimerFull;
		win.gameWindow.setTimer(win.moveTimerInternal);
		int col = AI.bestColumn(win.gameWindow.getBoard(), win.gameWindow.getDifficulty()); // calculate in different thread so we don't hang the main event thread
		win.gameWindow.toggleLock(); // disable lock
		win.gameWindow.toggleAllButtons();
		win.gameWindow.sendClick(col); // send click
		responseTimer = 0;
```

**Comment by vincentjguo** [comment] 2020-06-04 02:05
i assume that's because of the win checking thing method I used. I kinda just said screw time constraints and looped through every single token to find a win. Really bad method but it works

**Comment by potatoeggy** [comment] 2020-06-04 02:06
Yeah, even in normal difficulty it starts to take tens of seconds after just 20 or so chips.

**Comment by vincentjguo** [comment] 2020-06-04 02:06
ya AB pruning would help, but I should also find a way to optimize the win checking thing

**Comment by potatoeggy** [comment] 2020-06-04 02:07
try optimising by only checking if the last piece placed gives a win

**Comment by vincentjguo** [comment] 2020-06-04 02:09
Yes I tried doing that but the algo is made in a way where only at depth 0 could scoreGen/winchecking be called. So if at any other depth there is a win, it won't find it

**Comment by vincentjguo** [comment] 2020-06-04 02:10
Im probably going to make a visited array, and for every 4 tokens in every direction call winchecking again. This would reduce the time to check for a win by 4.

**Comment by vincentjguo** [comment] 2020-06-04 21:49
AI is less stupid as of 66958ad

**Comment by potatoeggy** [comment] 2020-06-04 21:51
"Stupid" is subjective, anyway, and there isn't any concrete issue that we can determine we've fixed or not. Smaller, more clear issues can be used in the future. Closing due to vagueness.

**Closed as completed by potatoeggy** 2020-06-04 21:51 UTC
Labels: backend, ai

**Comment by vincentjguo** [comment] 2020-06-04 21:54
Yep this was just an issue for me to rage about my stupidity lul.
